@startuml
autonumber
skinparam BoxPadding 10
skinparam ParticipantPadding 10

title Caso de Uso 2: Inscripción y Validación de Prerrequisitos

actor "Personal Admin" as Admin
participant "Sistema de\nControl Escolar" as System
database "Base de Datos\n(MySQL)" as DB

Admin -> System: Ingresa matrícula del estudiante
System -> DB: Consulta SELECT para recuperar objeto Estudiante
DB --> System: Retorna datos e historial académico
Admin -> System: Selecciona materias solicitadas para el semestre
System -> System: Cruza materias elegidas con la tabla de prerrequisitos

alt Prerrequisitos No Cumplidos o Estatus Pendiente
    System --> Admin: Interrumpe proceso y bloquea inscripción
else Prerrequisitos Validados Correctamente
    System -> DB: Guarda nuevo registro de asignación de horario
    DB --> System: Confirma transacción exitosa
    System --> Admin: Muestra comprobante de inscripción
end

@enduml